#!/bin/bash

sudo yum install java -y

#sudo echo "export JAVA_HOME=/opt/jdk-18.0.1" >> /etc/profile
#sudo echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile

aws s3 cp s3://shir11226543666123/Manager.jar .

java -jar Manager.jar

