#!/bin/bash

sudo yum install java -y

#sudo echo "export JAVA_HOME=/opt/jdk-18.0.1" >> /etc/profile
#sudo echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile

aws s3 cp s3://dspbucket12345/myapp-1.0.jar ./Worker.jar
aws s3 cp s3://dspbucket12345/stanford-parser.jar ./stanford-praser.jar
aws s3 cp s3://dspbucket12345/stanford-parser-models.jar ./stanford-praser-models.jar

java -jar Worker.jar