#!/bin/bash

sudo yum install java -y
sudo yum install maven -y

#sudo echo "export JAVA_HOME=/opt/jdk-18.0.1" >> /etc/profile
#sudo echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile

mvn package

sudo mvn exec:java -Dexec.mainClass="com.example.myapp.Worker"

aws s3 cp s3://dspbucket12345/myapp-1.0.jar ./Worker.jar

java -jar Worker.jar