#!/bin/bash

sudo yum install java -y

wget https://download.oracle.com/java/18/latest/jdk-18_linux-x64_bin.tar.gz

sudo mv jdk-18_linux-x64_bin.tar.gz /opt
cd /opt

sudo tar zxvf jdk-18_linux-x64_bin.tar.gz

sudo rm jdk-18_linux-x64_bin.tar.gz

sudo echo "export JAVA_HOME=/opt/jdk-18.0.1" >> /etc/profile
sudo echo "export PATH=$PATH:$JAVA_HOME/bin" >> /etc/profile

wget https://dspbucket12345.s3.us-west-2.amazonaws.com/myapp-1.0.jar

java -jar myapp-1.0.jar
# get the jar file of the local app from s3
# get the input file file from s3

# java -jar myapp.jar input.txt output.txt 5 [terminate]
